services:
  cisq2db:
    build: development/db
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "DB_APP_NAME=cisq2-hupol"
      - "DB_APP_USER=cisq2-hupol"
      - "DB_APP_PASS=cisq2-hupol"
    volumes:
      - "./development/db:/docker-entrypoint-initdb.d"
  hupol:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://cisq2db:5432/cisq2-hupol"